name: Uptime CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  repository_dispatch:
    types: [upptime]

jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
