name: Uptime CI
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  repository_dispatch:
    types: [upptime]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  uptime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: upptime/uptime-monitor@master
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
